### ISSUE TITLE
Some images translations gone, patcher deleting mods when not supposed to

### ISSUE THREAD

**Issue by Matihood1** [ManlyMarco/KK-HF_Patch#14]
So after installing the HF Patch v2.10 as per usual (I'm running Koikatu, I didn't select/deselect anything special in the installer), some images that used to be translated, like the hotkeys help window that appears after pressing F2), now turned Japanese.

I tried applying the patch again, selecting only the translations to be installed as well as choosing not to remove any mods.  Despite that, the patcher deleted all sideloader mods that were placed in folders inside of the mods folder (so all clothing, hair etc.). I don't think that was supposed to happen...

I've also noticed that the patcher restarts explorer.exe upon starting installation, which is pretty annoying.

**Comment by ManlyMarco** [comment]
Did only some image translations fail to load or all of them? Do they work now after reinstalling? Do you have afterschool and darkness expansions? It's likely an autotranslator bug.

HF Patch will remove sideloader modpacks even if you chose to not remove mods if you also uncheck sideloader modpacks in the to install list to allow uninstalling mods. The same is true for some other mods it installs.

explorer.exe is closed because it caused issues for some people if they opened game directory at some point and it didn't properly release the file locks, which ended up in the patch failing and a PC restart being required to try again or to be able to run the game again.

**Comment by Matihood1** [comment]
> Did only some image translations fail to load or all of them?
Only some of them, which makes it even stranger as I've gone through the translation files and they're all there, some of them are just not loading for whatever reason.
> Do they work now after reinstalling?
No. There was no change after reinstalling.
> Do you have afterschool and darkness expansions?
Yes, I do and that didn't cause any problems with the previous version of HF Patch.

I haven't done too much testing but a vast majority of the images seems to be loading. The ones that don't that I've noticed so far are [1920,1080,0,0]SpriteAtlasTexture-Free-2048x2048-fmt10 [91F2EB71CE-0000000000].png and shortcut_H [E42CC91B44-0000000000].png

**Comment by ManlyMarco** [comment]
Can you test if these translations work? Remove your old translations from BepInEx\Translation\en\Texture first https://github.com/IllusionMods/KoikatsuImageTranslation/releases/download/untagged-5eb305aada59b9a0d17e/Koikatsu.English.Image.Translation.v3.3.zip

**Comment by Matihood1** [comment]
The link is dead but I found and downloaded the file from the releases. Everything seems to be alright now. What was changed, compared to the files in the HF Patch?

**Comment by ManlyMarco** [comment]
Some files had to be renamed because of a change of how the translator plugin handled atlases, and the H hotkeys was a slightly different image added by one of the expansions.

So the issue is solved now?

**Comment by Matihood1** [comment]
Yes, all images are probably translated now.
