### ISSUE TITLE
Does the HF patch come with subtitiles for the dlc. Specifically the after school dlc?

### ISSUE THREAD

**Issue by LoveuMarko** [ManlyMarco/KK-HF_Patch#22]
Just wanted to know if this patch has subtitles for the afterschool dlc, and if not 
where to buy / download them from. 
Sowwy if I bothered you with this lame question. (◠﹏◠)

**Comment by ManlyMarco** [comment]
If you mean subtitles for H scenes, then you have to turn them on when installing the patch since they are all machine translated and bad quality.
There's no proper English translation for the AS DLC yet, it's being worked on. The patch has the latest available translations from the time it was released, there's nothing available to buy.
