### ISSUE TITLE
Strip the hf patch to Game patches only with no mods

### ISSUE THREAD

**Issue by proganime1200** [ManlyMarco/KK-HF_Patch#26]
What i need is just the game patches not some 11 gb patches with mods or is it the full game itself?

**Comment by ManlyMarco** [comment]
The patch doesn't include the game. It's done the way it is to make it as simple to use as possible and least likely to cause users to have issues and subsequently clog the help channels.

I would have to either make partial patches where you need to use mod updater to download only the mods that are missing (I experimented with this in previous patch versions and it failed because of massive server load, downloading through the updater takes a lot more bandwidth and can easily double the size of the full patch if you download from 0); or maintain two different versions of the patch (full patch for people coming in and a "no warranty given" version that the user is expected to only use after installing a recent version of the full patch). The second would increase support requests because people would install the wrong version or fail to update their mods and there's already a ton of support traffic, so I'd prefer not to do it.

**Comment by Qwart376** [comment]
You can also just make download for only the patches and list the mods, so people can download them at their own pace. Just write a short guide, people aren't point blank stupid

**Comment by ManlyMarco** [comment]
Done in latest release.
