### ISSUE TITLE
Steam Deck support

### ISSUE THREAD

**Issue by XargonWan** [ManlyMarco/KK-HF_Patch#45]
The game is running fine with Proton but no mods are loaded, even the translation.
Can you please make it compatible with the Steam Deck?

I'm up for testing if needed.

**Comment by ManlyMarco** [comment]
Check this guide https://docs.bepinex.dev/articles/advanced/steam_interop.html#open-winecfg-for-the-target-game

**Comment by m13253** [comment]
1. Use Discover Software Center to install Protontricks.
2. Run `com.github.Matoking.protontricks --gui`.
3. Select `コイカツ / Koikatsu Party: 1073440`. If there is no such option, run the game through Steam once first.
4. Wait a few seconds until a menu pops up, select `Select the default wineprefix`.
5. Select `Install a Windows DLL or component`.
6. Select `winhttp`.
7. The installation progress will be shown in the terminal window. Be patient.
8. After it’s done, click `Cancel` all the way back to close Protontricks.

There is a graphical glitch in the patched launcher: You can’t distinguish whether a check box is ticked or not.
You need to long press the check box to tell: If there is a faint white tick, this check box will be unchecked when you release the mouse. Otherwise, this check box will be checked when you release the mouse.

**Comment by ManlyMarco** [comment]
@m13253 Can you post the launcher issue here? https://github.com/IllusionMods/IllusionLaunchers
