### ISSUE TITLE
HF Patch 3.18 unable to edit Iris Overlay and there are 2 tabs for random character generator

### ISSUE THREAD

**Issue by lolersaurus** [ManlyMarco/KK-HF_Patch#59]
After installing 3.18, I can't seem to edit Iris Overlay. If I load a card with iris overlay already in it and then try to edit the iris, be it clear texture or load new texture, it will always revert back upon changing coordinate. What seems to be the problem?

Also, there are two tabs/options for random character generator in the character maker with seemingly same function.

**Comment by ManlyMarco** [comment]
Try installing v3.20

**Comment by lolersaurus** [comment]
I did as you said and installed v3.20 and removed all old plugin, the doubled random character generator is fixed, but the iris overlay problem stayed for some reason, any ideas?

**Comment by ManlyMarco** [comment]
Check if the per-coordinate toggle is checked and if it affects anything. Also check if the cards that have the issue use any MaterialEditor edits. You can try searching and asking in the help channel on the discord server to see if someone found a fix.

If the issue persists please post it here: https://github.com/ManlyMarco/Illusion-Overlay-Mods/issues
I'll close this issue since this repository is for the patch itself.
